"""Titrate live demo: a working constrained-BO loop over the CSTR simulator,
not a mockup. Every number on screen comes from the real titrate package --
the same physics, GP surrogate, and constrained-EI acquisition used in the
benchmark reported in the repository README.

Run with:  streamlit run webapp/app.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import streamlit as st  # noqa: E402

from titrate.environments.cstr_env import CSTREnvironment  # noqa: E402
from titrate.optimization.bo_loop import recommend_next_point  # noqa: E402
from titrate.baselines.lhs import propose as lhs_propose  # noqa: E402

st.set_page_config(page_title="Titrate", page_icon="\U0001f9ea", layout="wide")

N_INITIAL = 5
DIM_LABELS = {
    "temperature_K": "Temperature (K)",
    "residence_time_hr": "Residence time (hr)",
    "catalyst_loading_mol_pct": "Catalyst loading (mol%)",
}


@st.cache_resource
def load_environment() -> CSTREnvironment:
    env = CSTREnvironment()
    env.true_optimum()  # trigger + cache the differential_evolution solve once
    return env


@st.cache_data
def load_benchmark_trials() -> pd.DataFrame | None:
    path = REPO_ROOT / "results" / "benchmark_trials.csv"
    if not path.exists():
        return None
    return pd.read_csv(path)


def init_session_state(env: CSTREnvironment) -> None:
    if "X" in st.session_state:
        return
    rng = np.random.default_rng(0)
    X = lhs_propose(env.bounds, N_INITIAL, rng)
    objectives = np.empty(N_INITIAL)
    constraints = np.empty(N_INITIAL)
    for i, x in enumerate(X):
        result = env.evaluate(x, rng)
        objectives[i] = result.objective
        constraints[i] = result.constraint_value
    st.session_state.rng = rng
    st.session_state.X = X
    st.session_state.objectives = objectives
    st.session_state.constraints = constraints


def reset_session_state() -> None:
    for key in ("rng", "X", "objectives", "constraints"):
        st.session_state.pop(key, None)


def run_recommended_experiment(env: CSTREnvironment, x_next: np.ndarray) -> None:
    result = env.evaluate(x_next, st.session_state.rng)
    st.session_state.X = np.vstack([st.session_state.X, x_next])
    st.session_state.objectives = np.append(st.session_state.objectives, result.objective)
    st.session_state.constraints = np.append(st.session_state.constraints, result.constraint_value)


def render_header(env: CSTREnvironment, optimum) -> None:
    st.title("\U0001f9ea Titrate")
    st.caption(
        "Constrained Bayesian optimization for chemical process design — "
        "all data below is generated by a physics-based CSTR simulator, not real lab measurements. "
        "See the [GitHub repo](https://github.com/mojaffri/titrate) for the full benchmark and methodology."
    )

    X, objectives, constraints = st.session_state.X, st.session_state.objectives, st.session_state.constraints
    feasible = constraints <= env.constraint_max
    best_yield = objectives[feasible].max() if feasible.any() else float("nan")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Current best yield (observed)", f"{best_yield * 100:.1f}%")
    col2.metric("Experiments performed", f"{len(X)}")
    col3.metric("True optimum (ground truth)", f"{optimum.objective * 100:.1f}%")
    col4.metric("Feasible experiments so far", f"{int(feasible.sum())}/{len(X)}")


def render_constraints(env: CSTREnvironment) -> None:
    with st.expander("Engineering constraints", expanded=False):
        bounds = env.bounds
        st.markdown(
            f"- Temperature: {bounds[0, 0]:.0f} K – {bounds[0, 1]:.0f} K (safety / material limit)\n"
            f"- Residence time: {bounds[1, 0]:.1f} hr – {bounds[1, 1]:.1f} hr (reactor size / cost)\n"
            f"- Catalyst loading: {bounds[2, 0]:.1f} – {bounds[2, 1]:.1f} mol% (catalyst cost)\n"
            f"- Impurity concentration ≤ {env.constraint_max:.3f} mol/L (product purity spec — "
            f"a *soft*, nonlinear constraint, not a simple bound; this is what makes constrained BO matter)"
        )


def render_recommendation(env: CSTREnvironment) -> tuple:
    recommendation = recommend_next_point(
        env,
        st.session_state.X,
        st.session_state.objectives,
        st.session_state.constraints,
        st.session_state.rng,
        use_constraint=True,
    )
    _, std_at_point = recommendation.gp_objective.predict(np.atleast_2d(recommendation.x))

    st.subheader("Recommended next experiment")
    cols = st.columns(4)
    for col, dim_name, value in zip(cols, env.dimension_names, recommendation.x):
        col.metric(DIM_LABELS[dim_name], f"{value:.2f}")
    cols[3].metric("Expected improvement", f"+{recommendation.acquisition_value * 100:.2f} pp")
    st.caption(f"Model uncertainty at this point: ±{std_at_point[0] * 100:.1f} percentage points of yield")

    if st.button("▶ Run this experiment", type="primary"):
        run_recommended_experiment(env, recommendation.x)
        st.rerun()

    return recommendation


def render_data_table(env: CSTREnvironment) -> None:
    X, objectives, constraints = st.session_state.X, st.session_state.objectives, st.session_state.constraints
    df = pd.DataFrame(X, columns=[DIM_LABELS[d] for d in env.dimension_names])
    df["Observed yield"] = objectives
    df["Observed impurity"] = constraints
    df["Feasible"] = constraints <= env.constraint_max
    df.index = pd.RangeIndex(1, len(df) + 1, name="Experiment #")
    st.dataframe(df.style.format({"Observed yield": "{:.3f}", "Observed impurity": "{:.3f}"}), width="stretch")


def render_gp_slice(env: CSTREnvironment, recommendation) -> None:
    x_star = recommendation.x
    T_grid = np.linspace(env.bounds[0, 0], env.bounds[0, 1], 100)
    slice_X = np.column_stack(
        [T_grid, np.full_like(T_grid, x_star[1]), np.full_like(T_grid, x_star[2])]
    )
    mean, std = recommendation.gp_objective.predict(slice_X)
    true_yield = np.array([env.evaluate_noiseless(x).objective for x in slice_X])

    # Observed points off this 2D slice (different tau / Ccat) shouldn't be
    # expected to land on the curve -- fade them by distance from the slice
    # instead of plotting everything at full opacity, which would otherwise
    # look like the GP is wrong when it's really just a different point in
    # the other two dimensions.
    X = st.session_state.X
    other_dims_range = env.bounds[1:, 1] - env.bounds[1:, 0]
    normalized_dist = np.linalg.norm((X[:, 1:] - x_star[1:]) / other_dims_range, axis=1)
    alphas = np.clip(1.0 - normalized_dist, 0.08, 1.0)

    fig, ax = plt.subplots(figsize=(6, 4.5))
    ax.plot(T_grid, true_yield, color="black", linestyle="--", linewidth=1, label="True yield (ground truth)")
    ax.plot(T_grid, mean, color="#16a34a", label="GP prediction")
    ax.fill_between(T_grid, mean - 2 * std, mean + 2 * std, color="#16a34a", alpha=0.15, label="95% interval")
    for xi, yi, alpha in zip(X[:, 0], st.session_state.objectives, alphas):
        ax.scatter([xi], [yi], color="#374151", s=20, zorder=5, alpha=alpha)
    ax.scatter([], [], color="#374151", s=20, label="Observed data (faded = far from this slice)")
    ax.axvline(x_star[0], color="#a78bfa", linestyle=":", label="Recommended point")
    ax.set_xlabel("Temperature (K)")
    ax.set_ylabel("Yield")
    ax.set_title(f"GP surrogate slice (τ={x_star[1]:.2f} hr, C_cat={x_star[2]:.2f} mol%)")
    ax.legend(fontsize=7, loc="lower center")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)


def render_landscape(env: CSTREnvironment, recommendation) -> None:
    x_star = recommendation.x
    n_grid = 40
    T_grid = np.linspace(env.bounds[0, 0], env.bounds[0, 1], n_grid)
    tau_grid = np.linspace(env.bounds[1, 0], env.bounds[1, 1], n_grid)
    TT, TAU = np.meshgrid(T_grid, tau_grid)
    grid_points = np.column_stack([TT.ravel(), TAU.ravel(), np.full(TT.size, x_star[2])])

    mean, _ = recommendation.gp_objective.predict(grid_points)
    mean_grid = mean.reshape(TT.shape)

    feasibility_grid = None
    if recommendation.gp_constraint is not None:
        c_mean, c_std = recommendation.gp_constraint.predict(grid_points)
        from scipy.stats import norm

        p_feasible = norm.cdf((env.constraint_max - c_mean) / np.maximum(c_std, 1e-9))
        feasibility_grid = p_feasible.reshape(TT.shape)

    fig, ax = plt.subplots(figsize=(6, 4.5))
    contour = ax.contourf(TT, TAU, mean_grid, levels=20, cmap="viridis")
    fig.colorbar(contour, ax=ax, label="Predicted yield")
    if feasibility_grid is not None:
        ax.contour(TT, TAU, feasibility_grid, levels=[0.5], colors="red", linewidths=1.5, linestyles="--")
    ax.scatter(
        st.session_state.X[:, 0], st.session_state.X[:, 1], color="white", edgecolor="black", s=25, label="Observed"
    )
    ax.scatter([x_star[0]], [x_star[1]], color="#f59e0b", marker="*", s=250, edgecolor="black", label="Recommended", zorder=6)
    ax.set_xlabel("Temperature (K)")
    ax.set_ylabel("Residence time (hr)")
    ax.set_title(f"Predicted yield landscape (C_cat={x_star[2]:.2f} mol%)")
    ax.legend(fontsize=7, loc="lower right")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)
    st.caption("Red dashed line: the 50% feasibility contour from the constraint GP (impurity spec).")


def render_convergence(env: CSTREnvironment, optimum) -> None:
    X = st.session_state.X
    true_objectives = np.array([env.evaluate_noiseless(x).objective for x in X])
    true_constraints = np.array([env.evaluate_noiseless(x).constraint_value for x in X])
    is_feasible = true_constraints <= env.constraint_max

    best_so_far = np.full(len(X), np.nan)
    running_best = -np.inf
    for i in range(len(X)):
        if is_feasible[i] and true_objectives[i] > running_best:
            running_best = true_objectives[i]
        if running_best > -np.inf:
            best_so_far[i] = running_best

    fig, ax = plt.subplots(figsize=(6, 4.5))
    trials = load_benchmark_trials()
    if trials is not None:
        for strategy, label, color in [
            ("random", "Random search (benchmark median)", "#9ca3af"),
            ("lhs", "Latin Hypercube (benchmark median)", "#60a5fa"),
        ]:
            group = trials[trials["strategy"] == strategy]
            median = group.groupby("iteration")["best_feasible_so_far"].median()
            ax.plot(median.index, median.values, color=color, linestyle="--", linewidth=1, label=label)

    ax.plot(np.arange(1, len(X) + 1), best_so_far, color="#16a34a", linewidth=2, label="This session (constrained BO)")
    ax.axhline(optimum.objective, color="black", linestyle=":", linewidth=1, label="True optimum")
    ax.set_xlabel("Experiments performed")
    ax.set_ylabel("Best feasible yield found so far (ground truth)")
    ax.set_title("This session vs. the 40-seed benchmark medians")
    ax.legend(fontsize=7)
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)
    st.caption(
        "Scored against the noiseless ground-truth simulator, matching the benchmark methodology in the README "
        "(not the noisy values actually observed during the session)."
    )


def main() -> None:
    env = load_environment()
    optimum = env.true_optimum()
    init_session_state(env)

    render_header(env, optimum)
    render_constraints(env)

    if st.button("↺ Reset session"):
        reset_session_state()
        st.rerun()

    recommendation = render_recommendation(env)

    tab_data, tab_slice, tab_landscape, tab_convergence = st.tabs(
        ["Experimental data", "GP prediction slice", "Optimization landscape", "Convergence vs. baselines"]
    )
    with tab_data:
        render_data_table(env)
    with tab_slice:
        render_gp_slice(env, recommendation)
    with tab_landscape:
        render_landscape(env, recommendation)
    with tab_convergence:
        render_convergence(env, optimum)


if __name__ == "__main__":
    main()
