[theme]
base = "light"
primaryColor = "#0F8F8B"
backgroundColor = "#F2F6F8"
secondaryBackgroundColor = "#E8F0F3"
textColor = "#12243A"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
